### ISSUE TITLE
Override default user password

### ISSUE THREAD

**Issue by omelnyk** [Hitchwiki/hitchwiki#138]
Add a way to do it in `settings.ini` for Hitchwiki, Hitchhiker and Hitchbot users

**Comment by simison** [comment]
You mean the SQL or the admin user created on dev-install?

**Comment by omelnyk** [comment]
These: [scripts/create_users.sh#L21-L34](https://github.com/Hitchwiki/hitchwiki/blob/b16c8e82f46d8776d0beb693565675156ad1a77a/scripts/create_users.sh#L21-L34)

**Comment by traumschule** [comment]
they are hardcoded in ansible right now. i could add a hash under hitchwiki like this:
```
hitchwiki:
  user:
    Hitchwiki: {{ db.phpmyadmin_password }}
    Hitchbot: {{ db.phpmyadmin_password }}
    Hitchhiker:  {{ db.phpmyadmin_password }}
```
so you could change them easily later on
